config/routes.rb
Genial::Application.routes.draw do
  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  resources :categories

  get "store/index"

  resources :products

  root :to => 'store#index', :as => 'store'

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/models/category.rb
class Category < ActiveRecord::Base
  attr_accessible :name
  validates :name, :presence => true
  validates :name, :uniqueness => true
  has_many:products
end

app/models/product.rb
class Product < ActiveRecord::Base
  default_scope :order => 'title'
  belongs_to:category
  attr_accessible :cost_price, :picture, :sale_price, :title, :description, :category_id
  validates :title, :description, :picture, :presence => true
  validates :cost_price, :numericality => {:greater_than_or_equal_to => 0.01}
  validates :title, :uniqueness => true
  validates :picture, :format => {
    :with=> %r{\.(gif|jpg|png)$}i,
    :message => 'Pueden ser imagenes GIF, JPG or PNG.'
  }
  mount_uploader :picture, PictureUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @categories }
    end
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
    @search = Product.ransack(params[:q])
    @category = Category.find(params[:id])
    @products = @category.products
    @categories = Category.all

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @category }
    end
  end

  # GET /categories/new
  # GET /categories/new.json
  def new
    @category = Category.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @category }
    end
  end

  # GET /categories/1/edit
  def edit
    @category = Category.find(params[:id])
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(params[:category])

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render json: @category, status: :created, location: @category }
      else
        format.html { render action: "new" }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /categories/1
  # PUT /categories/1.json
  def update
    @category = Category.find(params[:id])

    respond_to do |format|
      if @category.update_attributes(params[:category])
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category = Category.find(params[:id])
    @category.destroy

    respond_to do |format|
      format.html { redirect_to categories_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  # GET /products
  # GET /products.json
  
  def index
    @search = Product.ransack(params[:q])
    @products = @search.result  
    @search.build_condition
    @categories = Category.all
    
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @products }
    end
  end

  # GET /products/1
  # GET /products/1.json
  def show
    @product = Product.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @product }
    end
  end

  # GET /products/new
  # GET /products/new.json
  def new
    @product = Product.new
    @categories = Category.all
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @product }
    end
  end

  # GET /products/1/edit
  def edit
    @product = Product.find(params[:id])
    @categories = Category.all
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(params[:product])
     
    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render json: @product, status: :created, location: @product }
      else
        format.html { render action: "new" }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /products/1
  # PUT /products/1.json
  def update
    @product = Product.find(params[:id])

    respond_to do |format|
      if @product.update_attributes(params[:product])
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product = Product.find(params[:id])
    @product.destroy

    respond_to do |format|
      format.html { redirect_to products_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/store_controller.rb
class StoreController < ApplicationController
  def index
   @search = Product.ransack(params[:q])
   @products = @search.result
   @search.build_condition
   @categories = Category.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/store_helper.rb
module StoreHelper
end

app/views/categories/_form.html.erb
<%= form_for(@category) do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
    <% @category.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>

<% end %>

app/views/categories/_index.html.erb
<ul>
  <% @categories.each do |category| %>
     <li><%= link_to category.name, category %></li>
  <% end %>
</ul>

app/views/categories/edit.html.erb
<h1>Editing category</h1>

<%= render 'form' %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<h1>Listing categories</h1>

<table>
  <tr>
    <th> nombre</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @categories.each do |category| %>
  <tr>
    <td><%= category. name %></td>
    <td><%= link_to 'Show', category %></td>
    <td><%= link_to 'Edit', edit_category_path(category) %></td>
    <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Category', new_category_path %>

app/views/categories/new.html.erb
<h1>New category</h1>

<%= render 'form' %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<div id="content">
  <p id="notice"><%= notice %></p>

  <p>
   <b> nombre:</b>
   <%= @category. name %>
  </p>

  <% unless @products.empty? %>
    <div class="products">
      <div class="cl">&nbsp;</div>
      <ul>
        <%= render :partial => "products/index" %>
      </ul>
      <div class="cl">&nbsp;</div>
      </br></br>
    </div>
  <% end %>
</div>
<!-- End Content -->

<!-- Buscador y categorias -->
<%= render :partial => 'store/nav_left', :local => @categories %>
    
<div class="cl">&nbsp;</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Genial</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<!-- Shell -->	
<div class="shell">
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
  <div id="header">
    <h1 id="logo">
      <a href="#">Genial Indumentaria</a>
    </h1>
    <!-- Navigation -->
    <%= render :partial => 'store/nav' %> 
  </div>  
  <!-- Main -->
  <div id="main">
    <%= yield %>
  </div>
  <!-- End main -->    
</div>	
<!-- End Shell -->    
</body>
</html>

app/views/products/_form.html.erb
<%= form_for(@product, :html => { :multipart => true }) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field" >
    <%= f.label :description %><br />
    <%= f.text_area :description, :rows => 6 %>
  </div>
  
  
  <div class="field" >
   <%= collection_select(:product, :category_id, @categories, :id, :name)%>
  </div>
  
  
  <div class="field">
    <%= f.label :picture %><br />
    <%= f.file_field :picture %>
  </div>
   

  <div class="field">
    <%= f.label :cost_price %><br />
    <%= f.text_field :cost_price %>
  </div>
  <div class="field">
    <%= f.label :sale_price %><br />
    <%= f.text_field :sale_price %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/_index.html.erb
<% @products.each do |product| %>
      <li>
        <%=link_to( image_tag(product.picture), product) %>
	 <div class="product-info">
          <h3>Genial</h3>
          <div class="product-desc">
	    <h4><%= product.title %></h4>
	    <p><%= product.description %></p>
            <strong class="price"><%= product.sale_price %></strong>
           </div>
             
        </div></br></br>
        
      </li>
      
<% end %>

app/views/products/edit.html.erb
<h1>Editing product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
 <!-- Main -->
  <div id="main">
    
    <!-- Content -->
    <div id="content">  
      
      <!-- End Content Slider -->
      
      <!-- Products -->
      <div class="products">
        <div class="cl">&nbsp;</div>
        <ul>
          <%= render :partial => 'index' %>
          
        </ul>
        
        <div class="cl">&nbsp;</div>
        </br></br>
        
      </div>
      <!-- End Products -->
                        
    </div>
    <!-- End Content -->
    
    <!-- Buscador -->
    <%= render :partial => 'store/nav_left' %>
    
    <div class="cl">&nbsp;</div>
  </div>
  <!-- End Main -->	
  

app/views/products/new.html.erb
<h1>New product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @product.title %>
</p>

<p>
  <b>Picture:</b>
  <%= image_tag(@product.picture_url) if @product.picture.present? %>
</p>

<p>
  <b>Sale price:</b>
  <%= @product.sale_price %>
</p>

app/views/store/_nav.html.erb
<div id="navigation">
  <ul>
    
    <li><%= link_to "Home", :controller => "store", :action => "index" %> </li> 
    <li><a href="#">Contacto</a></li>
  </ul>
</div>

app/views/store/_nav_left.html.erb
<!-- Sidebar -->
<div id="sidebar">
  <!-- Search -->
  <div class="box search">
    <h2>Search by <span></span></h2>
    <div class="box-content">
      <%= search_form_for @search do |f| %>
          <%= f.label :title_cont, "Producto" %>
          <div class="field">
            <%= f.text_field :title_cont %>
          </div>
          
          <%= f.label :"Categoria" %>
          <div class="field" >
              <%= collection_select(:q, :category_id_eq, @categories, :id, 
                :name, {:include_blank => '- Seleccione Categoria -'})%>
          </div>
          
          <input type="submit" class="search-submit" value="Search" />
      <% end %>


    </div>
    <!-- End box-content -->
         
  </div>
  <!-- End box search -->
     
  <!-- Categories -->
  <div class="box categories">
    <h2>Categorias <span></span></h2>
    <div class="box-content">
      <%= render :partial => 'categories/index' %>
           
    </div>
         <!-- End box-content -->
  </div>
      
</div>
<!-- End Sidebar -->

app/views/store/_slider.html.erb
 <!-- Content Slider Foto local-->
  <div id="slider" class="box">
    <div id="slider-holder">
        <ul>
          <li><a href="#"><img src="/assets/slide1.jpg" alt="" /></a></li>
	  <li><a href="#"><img src="/assets/slide1.jpg" alt="" /></a></li>
	  <li><a href="#"><img src="/assets/slide1.jpg" alt="" /></a></li>
	  <li><a href="#"><img src="/assets/slide1.jpg" alt="" /></a></li>
    </ul>
  </div>
        <!-- End slider-holder -->
        
  <div id="slider-nav">
      <a href="#" class="active">1</a>
      <a href="#">2</a>
      <a href="#">3</a>
      <a href="#">4</a>
  </div>
  <!-- End slider-nav -->

app/views/store/index.html.erb
 <!-- Main -->
  <div id="main">
    
    <!-- Content -->
    <div id="content">  
      <!-- slider-nav -->
        <%= render :partial => 'slider' %>
      
      </div>
      <!-- End Content Slider -->
      
      <!-- Products -->
      <div class="products">
        <div class="cl">&nbsp;</div>
        <ul>
          <%= render :partial => 'products/index' %>
          
        </ul>
        
        <div class="cl">&nbsp;</div>
        </br></br>
        
      </div>
      <!-- End Products -->
                        
    </div>
    <!-- End Content -->
    
    <!-- Buscador -->
    <%= render :partial => 'nav_left' %>
    
    <div class="cl">&nbsp;</div>
  </div>
  <!-- End Main -->	
  